baseURL = 'https://www.osteochloe.fr'
languageCode = 'fr-FR'
defaultContentLanguage = "fr"
paginate = "5" # Nombre d articles par page dans une vue de type list (ex. : blog)

title = 'Chloé Pequignot | OA 1176 | Ostéopathe animalière'


################################# Default parameters ##########################
[params]
logo = "images/logo/logo_chloe.jpeg"
description = "Chloé Pequignot | OA 1176 | Ostéopathe animalière"
desc_footer = "Ostéopathe animalière"
author = "Chloé Pequignot | OA 1176"
bgi_title = "images/general/odin-moi.jpeg"
definition = "Prévention et/ou traitement des troubles fonctionnels du corps de l'animal (à l'exclusion des pathologies organiques qui nécessitent une intervention thérapeutique, médicale, chirurgicale, médicamenteuse ou par agents physiques)."

[params.contact]
email = "chloe.osteo.animalier@gmail.com"
phone = "+ 33 7 66 77 97 07"
address = "Audincourt - Déplacement à domicile uniquement" #9 av Aristide Briand, 25400 Audincourt Je vais mettre juste la ville, sinon on va sonner chez moi
map_latitude = "47.4823625"
map_longitude = "6.8407664"
############################### Mail form parameters ###########################
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = true
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "#"

[[params.opening]]
day = "Lundi au Vendredi"
hour = "10h-18h"

#[[params.opening]]
#day = "Mercredi au Vendredi"
#hour = "10h-18h"

################################# Social Media ################################
[[params.social]]
icon = "fa-google-plus-g" 
link = "#"
aria = "Google plus"

#[[params.social]]
#icon = "fa-linkedin" 
#link = "#"
#aria = "LinkedIn"

#[[params.social]]
#icon = "fa-pinterest" 
#link = "#"
#aria = "Pinterest"

[[params.social]]
icon = "fa-instagram" 
link = "https://instagram.com/pequignot_osteoanimalier"
aria = "Instagram"

#[[params.social]]
#icon = "fa-twitter" 
#link = "#"
#aria = "Twitter"

[[params.social]]
icon = "fa-facebook-f" 
link = "https://www.facebook.com/profile.php?id=100086706158647"
aria = "Facebook"

############################## Références externes #############################
[[params.external]]
icon = "images/logo/ffoa.png"
name = "Fédération Française d'Ostéopathie Animale"
url = "https://www.ffao.fr"
weight = 1

[[params.external]]
icon = "images/logo/fnoa.png"
name = "Fédération Nationale d'Ostéopathie Animale"
url = "https://www.fnao.fr"
weight = 2

[[params.external]]
icon = "images/logo/onv.jpg"
name = "Ordre National des Vétérinaires"
url = "https://www.veterinaire.fr/la-profession-veterinaire/nos-grands-dossiers/osteopathie-animale"
weight = 3

[[params.external]]
icon = "images/logo/SPA Mulhouse.jpeg"
name = "SPA Mulhouse"
url = "https://www.spa-mulhouse.fr/"
weight = 4

################################################################################
[languages]
  [languages.fr]
    contentDir = "content/fr"
    languageName = "French"
    weight = 1

[[languages.fr.menu.main]]
hasChildren = true
weight = 6
name = "Plus"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

################################# Preloader ###################################
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif image

################################# widgets side bar #############################
[params.widgets]
sidebar = ["taxonomy_category", "taxonomy_tags"]

################################# plugins ######################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/fancybox/jquery.fancybox.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/fontawesome/css/all.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/animation/animate.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/jquery-ui/jquery-ui.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/leaflet/leaflet.css"
attributes = "crossorigin=''"

[[params.plugins.css]]
link = "plugins/timePicker/timePicker.css"
attributes = ""

[[params.plugins.css]]
link = "css/style.css"
attributes = "media='screen'"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick-animation.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/fancybox/jquery.fancybox.min.js"
attributes = "defer"

[[params.plugins.js]]
link = "plugins/jquery-ui/jquery-ui.js"
attributes = "defer"

[[params.plugins.js]]
link = "plugins/timePicker/timePicker.js"
attributes = "defer"

[[params.plugins.js]]
link = "js/script.js"
attributes = ""
